name: Check Nexus Credentials

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  push:
    branches:
      - master
    paths:
      - '.github/workflows/check-nexus-credentials.yaml' # this file
  workflow_dispatch:

jobs:
  check-nexus-credentials:
    runs-on: [mtc-self-hosted,mtc-tha]
    steps:
      # Setup
      - name: HTTP HEAD to mulesoft-ee Maven Nexus repo with credentials from GitHub Secrets
        run: curl -k --fail --head -u "$EE_UNAME:$EE_PASSW" https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/
        env:
          EE_UNAME: ${{ secrets.RELEASES_EE_USERNAME }}
          EE_PASSW: ${{ secrets.RELEASES_EE_PASSWORD }}

