name: CICD custom-message-logging-policy

on:
  push:
    branches:
      - master
    paths:
      - 'solutions/final/api-policies/custom-message-logging-policy/**'             # the base dir for this build and deployment unit
      - 'solutions/final/api-policies/parent-pom/parent.xml'                        # direct parent POM
      - 'solutions/bom/pom.xml'                                                     # top-level parent POM
      - 'solutions/parent-pom/pom.xml'                                              # BOM
      - '.github/workflows/cicd-solutions-final-custom-message-logging-policy.yaml' # this file
  workflow_dispatch:

env:
  BASE_DIR:     solutions/final/api-policies/custom-message-logging-policy
  TEST_REPORTS: test-reports-solutions-final-custom-message-logging-policy
  ENC_KEY:      ${{ secrets.FINAL_ENCRYPT_KEY }}

jobs:
  build-test-deploy:
    runs-on: [mtc-self-hosted,mtc-tha]
    steps:
      # Setup
      - name: Clear repository
        run: sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
      - name: Set up JDK 1.8 and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Create settings.xml with credentials from GitHub Secrets
        run: ./solutions/etc/create-settings-xml-from-template.sh "$EE_UNAME" "$EE_PASSW" "$EX_UNAME" "$EX_PASSW" "$EX_UNAME" "$EX_PASSW" "$DPL_EX_UNAME" "$DPL_EX_PASSW"
        env:
          EE_UNAME: ${{ secrets.RELEASES_EE_USERNAME }}
          EE_PASSW: ${{ secrets.RELEASES_EE_PASSWORD }}
          # just for reading from Exchange:
          EX_UNAME: ${{ secrets.EXCHG_VIEWER_USERNAME }}
          EX_PASSW: ${{ secrets.EXCHG_VIEWER_PASSWORD }}
          # deploys to Exchange
          DPL_EX_UNAME: ${{ secrets.EXCHG_CONTRIB_USERNAME }}
          DPL_EX_PASSW: ${{ secrets.EXCHG_CONTRIB_PASSWORD }}
      # Build and test
      - name: 'Full build incl. unit tests, package, and install into local Maven repo'
        working-directory: ${{ env.BASE_DIR }}
        run: ./build.sh "$ENC_KEY"
      # Archive artifacts
      # - name: Collect test reports
      #   # Copy all target/site directories anywhere under the working directory into a directory called $TEST_REPORTS
      #   # preserving the original directory hierarchy under the working directory
      #   working-directory: ${{ env.BASE_DIR }}
      #   run: |
      #     mkdir $TEST_REPORTS
      #     find . -type d -path '*/target/site' | xargs tar c | tar x -C $TEST_REPORTS
      # - name: Archive test reports
      #   # Archive everything under the $TEST_REPORTS directory under that very name
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: ${{ env.TEST_REPORTS }}
      #     path: ${{ env.BASE_DIR }}/${{ env.TEST_REPORTS }}
      # Deploy
      - name: Deploy to Exchange
        working-directory: ${{ env.BASE_DIR }}
        run: ./deploy.sh
